// <auto-generated />
using GestorProjetosTarefas.Shared.Data.BD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorProjetosTarefas.Shared.Data.Migrations
{
    [DbContext(typeof(GestorProjetosTarefasContext))]
    [Migration("20250520184250_RelateEmpregadoProjeto")]
    partial class RelateEmpregadoProjeto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmpregadoProjeto", b =>
                {
                    b.Property<int>("EmpregadoId")
                        .HasColumnType("int");

                    b.Property<int>("ProjetosId")
                        .HasColumnType("int");

                    b.HasKey("EmpregadoId", "ProjetosId");

                    b.HasIndex("ProjetosId");

                    b.ToTable("EmpregadoProjeto");
                });

            modelBuilder.Entity("GestorProjetosTarefas.Shared.Models.Empregado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empregado");
                });

            modelBuilder.Entity("GestorProjetosTarefas.Shared.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Orcamento")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Projeto");
                });

            modelBuilder.Entity("GestorProjetosTarefas.Shared.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracaoDias")
                        .HasColumnType("int");

                    b.Property<int?>("EmpregadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpregadoId");

                    b.ToTable("Tarefa");
                });

            modelBuilder.Entity("EmpregadoProjeto", b =>
                {
                    b.HasOne("GestorProjetosTarefas.Shared.Models.Empregado", null)
                        .WithMany()
                        .HasForeignKey("EmpregadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorProjetosTarefas.Shared.Models.Projeto", null)
                        .WithMany()
                        .HasForeignKey("ProjetosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorProjetosTarefas.Shared.Models.Tarefa", b =>
                {
                    b.HasOne("GestorProjetosTarefas.Shared.Models.Empregado", "Empregado")
                        .WithMany("Tarefas")
                        .HasForeignKey("EmpregadoId");

                    b.Navigation("Empregado");
                });

            modelBuilder.Entity("GestorProjetosTarefas.Shared.Models.Empregado", b =>
                {
                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
